// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileStore.Services;

#nullable disable

namespace MobileStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241013083714_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobileStore.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(1453),
                            ImageFileName = "samsung.jpg",
                            IsActive = true,
                            Name = "سامسونگ",
                            Slug = "samsung"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(1466),
                            ImageFileName = "nokia.jpg",
                            IsActive = true,
                            Name = "نوکیا",
                            Slug = "nokia"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(1468),
                            ImageFileName = "xiaomi.jpg",
                            IsActive = true,
                            Name = "شیائومی",
                            Slug = "xiaomi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(1470),
                            ImageFileName = "apple.jpg",
                            IsActive = true,
                            Name = "اپل",
                            Slug = "apple"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(1472),
                            ImageFileName = "huawei.jpg",
                            IsActive = true,
                            Name = "هوآوی",
                            Slug = "huawei"
                        });
                });

            modelBuilder.Entity("MobileStore.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MobileStore.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Galleries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2322),
                            ImageFileName = "samsung-a14-1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2325),
                            ImageFileName = "samsung-a14-2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2327),
                            ImageFileName = "huawei-nova-y71-1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2328),
                            ImageFileName = "huawei-nova-y71-2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2330),
                            ImageFileName = "huawei-nova-y71-3.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2331),
                            ImageFileName = "xiaomi-redmi-note-13-1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2333),
                            ImageFileName = "Galaxy-A05-1.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2334),
                            ImageFileName = "Galaxy-A05-2.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2335),
                            ImageFileName = "Galaxy-M13-1.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2337),
                            ImageFileName = "Galaxy-M13-2.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2338),
                            ImageFileName = "Galaxy-M13-3.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2339),
                            ImageFileName = "Galaxy-A15-1.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2341),
                            ImageFileName = "Galaxy-A15-2.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2342),
                            ImageFileName = "Galaxy-A15-3.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2343),
                            ImageFileName = "Galaxy-A05s-1.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2344),
                            ImageFileName = "Galaxy-A05s-2.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2346),
                            ImageFileName = "Galaxy-A05s-3.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2347),
                            ImageFileName = "Galaxy-A23-1.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2348),
                            ImageFileName = "Galaxy-A23-2.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2349),
                            ImageFileName = "Galaxy-A23-3.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2351),
                            ImageFileName = "Galaxy-A25-1.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2352),
                            ImageFileName = "Galaxy-A25-2.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2353),
                            ImageFileName = "Galaxy-A25-3.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2354),
                            ImageFileName = "Galaxy-A34-1.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2356),
                            ImageFileName = "Galaxy-A34-2.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2357),
                            ImageFileName = "Galaxy-A35-1.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2358),
                            ImageFileName = "Galaxy-A35-2.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2359),
                            ImageFileName = "Galaxy-A54-1.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2361),
                            ImageFileName = "Galaxy-A54-2.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2363),
                            ImageFileName = "Galaxy-A55-1.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2364),
                            ImageFileName = "Galaxy-A55-2.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2365),
                            ImageFileName = "Galaxy-A55-3.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2370),
                            ImageFileName = "Galaxy-S21-1.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2371),
                            ImageFileName = "Galaxy-S23-1.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2373),
                            ImageFileName = "Galaxy-S23-2.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2374),
                            ImageFileName = "Galaxy-S23-Ultra-1.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2376),
                            ImageFileName = "Galaxy-S24-Ultra-1.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2377),
                            ImageFileName = "Galaxy-S24-Ultra-2.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2378),
                            ImageFileName = "Galaxy-S24-Ultra-3.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2380),
                            ImageFileName = "Redmi-Note-12S-1.jpg",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2381),
                            ImageFileName = "Redmi-Note-12S-2.jpg",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2383),
                            ImageFileName = "Redmi-Note-13-1.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2384),
                            ImageFileName = "Redmi-Note-13-2.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2385),
                            ImageFileName = "Redmi-Note-13-3.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2387),
                            ImageFileName = "Redmi-Note-12-1.jpg",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2388),
                            ImageFileName = "Redmi-Note-12-Turbo-1.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2390),
                            ImageFileName = "Redmi-Note-12-Turbo-2.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2391),
                            ImageFileName = "Redmi-Note-12-Turbo-3.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2393),
                            ImageFileName = "Poco-F5-1.jpg",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2394),
                            ImageFileName = "Poco-F5-2.jpg",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2395),
                            ImageFileName = "Poco-F5-3.jpg",
                            ProductId = 23
                        });
                });

            modelBuilder.Entity("MobileStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MobileStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Camera")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hard")
                        .HasColumnType("int");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2133),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A14"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2138),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi 12"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 5,
                            Camera = 48,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2141),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل هوآوی مدل nova Y71"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2144),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 13 4G"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2219),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A05"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2223),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy M13"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2226),
                            Description = "",
                            Hard = 128,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A15"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2230),
                            Description = "",
                            Hard = 128,
                            Ram = 6,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A05s"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2233),
                            Description = "",
                            Hard = 64,
                            Ram = 4,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A23 "
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2237),
                            Description = "",
                            Hard = 128,
                            Ram = 6,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A25"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            Camera = 48,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2241),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A34 5G "
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2244),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A35"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2247),
                            Description = "",
                            Hard = 128,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A54 5G"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2251),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy A55"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 1,
                            Camera = 12,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2254),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S21 FE 5G"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 1,
                            Camera = 50,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2257),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S23 FE"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 1,
                            Camera = 200,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2260),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S23 Ultra"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            Camera = 200,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2264),
                            Description = "",
                            Hard = 512,
                            Ram = 12,
                            Title = "گوشی موبایل سامسونگ مدل Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2267),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 12S"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2270),
                            Description = "",
                            Hard = 256,
                            Ram = 8,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 13 5G"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 3,
                            Camera = 108,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2274),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 12 Pro 5G"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 3,
                            Camera = 64,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2277),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل شیائومی مدل Redmi Note 12 Turbo 5G"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 3,
                            Camera = 64,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2280),
                            Description = "",
                            Hard = 256,
                            Ram = 12,
                            Title = "گوشی موبایل شیائومی مدل Poco F5 5G"
                        });
                });

            modelBuilder.Entity("MobileStore.Models.ProductToShop", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ShopId");

                    b.HasIndex("ShopId");

                    b.ToTable("ProductToShops");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ShopId = 1,
                            Price = 6000000
                        },
                        new
                        {
                            ProductId = 2,
                            ShopId = 1,
                            Price = 6900000
                        },
                        new
                        {
                            ProductId = 3,
                            ShopId = 1,
                            Price = 6200000
                        },
                        new
                        {
                            ProductId = 4,
                            ShopId = 1,
                            Price = 8840000
                        },
                        new
                        {
                            ProductId = 5,
                            ShopId = 1,
                            Price = 8740000
                        },
                        new
                        {
                            ProductId = 6,
                            ShopId = 1,
                            Price = 5699000
                        },
                        new
                        {
                            ProductId = 7,
                            ShopId = 1,
                            Price = 6079000
                        },
                        new
                        {
                            ProductId = 8,
                            ShopId = 1,
                            Price = 6470000
                        },
                        new
                        {
                            ProductId = 9,
                            ShopId = 1,
                            Price = 7399000
                        },
                        new
                        {
                            ProductId = 10,
                            ShopId = 1,
                            Price = 9549000
                        },
                        new
                        {
                            ProductId = 11,
                            ShopId = 1,
                            Price = 12999000
                        },
                        new
                        {
                            ProductId = 12,
                            ShopId = 1,
                            Price = 15287000
                        },
                        new
                        {
                            ProductId = 13,
                            ShopId = 1,
                            Price = 16990000
                        },
                        new
                        {
                            ProductId = 14,
                            ShopId = 1,
                            Price = 20980000
                        },
                        new
                        {
                            ProductId = 15,
                            ShopId = 1,
                            Price = 21150000
                        },
                        new
                        {
                            ProductId = 16,
                            ShopId = 1,
                            Price = 25850000
                        },
                        new
                        {
                            ProductId = 17,
                            ShopId = 1,
                            Price = 57950000
                        },
                        new
                        {
                            ProductId = 19,
                            ShopId = 1,
                            Price = 8530000
                        },
                        new
                        {
                            ProductId = 20,
                            ShopId = 1,
                            Price = 11540000
                        },
                        new
                        {
                            ProductId = 21,
                            ShopId = 1,
                            Price = 12600000
                        },
                        new
                        {
                            ProductId = 22,
                            ShopId = 1,
                            Price = 18799000
                        },
                        new
                        {
                            ProductId = 23,
                            ShopId = 1,
                            Price = 17999000
                        },
                        new
                        {
                            ProductId = 2,
                            ShopId = 2,
                            Price = 6950000
                        },
                        new
                        {
                            ProductId = 20,
                            ShopId = 2,
                            Price = 11440000
                        },
                        new
                        {
                            ProductId = 10,
                            ShopId = 2,
                            Price = 9549000
                        });
                });

            modelBuilder.Entity("MobileStore.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(1703),
                            Name = "موبایل404",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(1706),
                            Name = "علی شاپ",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MobileStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2010),
                            Email = "admin@gmail.com",
                            IsActive = false,
                            Name = "ادمین",
                            Password = "81-DC-9B-DB-52-D0-4D-C2-00-36-DB-D8-31-3E-D0-55",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2058),
                            Email = "ali@gmail.com",
                            IsActive = false,
                            Name = "علی",
                            Password = "81-DC-9B-DB-52-D0-4D-C2-00-36-DB-D8-31-3E-D0-55",
                            Role = "seller"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 10, 13, 12, 7, 14, 416, DateTimeKind.Local).AddTicks(2083),
                            Email = "tara@gmail.com",
                            IsActive = false,
                            Name = "تارا",
                            Password = "81-DC-9B-DB-52-D0-4D-C2-00-36-DB-D8-31-3E-D0-55",
                            Role = "client"
                        });
                });

            modelBuilder.Entity("MobileStore.Models.Comment", b =>
                {
                    b.HasOne("MobileStore.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileStore.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MobileStore.Models.Gallery", b =>
                {
                    b.HasOne("MobileStore.Models.Product", "Product")
                        .WithMany("Galleries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MobileStore.Models.Order", b =>
                {
                    b.HasOne("MobileStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileStore.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.HasOne("MobileStore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MobileStore.Models.Product", b =>
                {
                    b.HasOne("MobileStore.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("MobileStore.Models.ProductToShop", b =>
                {
                    b.HasOne("MobileStore.Models.Product", "Product")
                        .WithMany("ProductToShops")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileStore.Models.Shop", "Shop")
                        .WithMany("ProductToShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("MobileStore.Models.Shop", b =>
                {
                    b.HasOne("MobileStore.Models.User", "User")
                        .WithMany("Shop")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MobileStore.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MobileStore.Models.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Galleries");

                    b.Navigation("ProductToShops");
                });

            modelBuilder.Entity("MobileStore.Models.Shop", b =>
                {
                    b.Navigation("ProductToShops");
                });

            modelBuilder.Entity("MobileStore.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
